name: build-test

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04,windows-latest]
        lazarus-versions: [1.8.2]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gerryferdinandus/setup-lazarus@v2.2.6
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    - name: Build the Main Application
      run: lazbuild --build-mode=Release "source/project/tracker_editor/trackereditor.lpi"
    - name: Build the Unit Tests Application
      run: lazbuild --build-mode=Debug "source/project/unit_test/tracker_editor_test.lpi"
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./ #optional
        run: enduser/test_trackereditor -a --format=plain
    - name: Clean up after test
      shell: bash
      run: |
        rm -f enduser/console_log.txt
        rm -f enduser/export_trackers.txt
        git reset --hard
