# Tests building lazbuild using fplazup on Windows 32, Windows 64, Linux 64, MacOS 64 and AArch64 (cross compiled)
# Builds FPC 3.2.0 & Lazarus trunk but reverts to a known revision that compiles (64045).

name: Test

on: push

jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: 'Windows 32'
            lazarus-url : 'https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2032%20bits/Lazarus%202.0.12/lazarus-2.0.12-fpc-3.2.0-win32.exe/download' 


    steps:
    - uses: actions/checkout@v2
    - name: Install win 32 version
      if: matrix.config.os == 'windows-latest'
      run: |
        curl --retry 5 -L -o lazarus.exe ${{ matrix.config.lazarus-url }}
        ./lazarus.exe /VERYSILENT /DIR="c:\lazarus"
        echo $GITHUB_PATH
        echo "c:\lazarus" >> $GITHUB_PATH
        echo $GITHUB_PATH
        lazbuild --help
    - name: Install Dependencies (Ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -m -y install libgtk2.0-dev libpango1.0-dev
    - name: Install Lazarus on (Ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        curl --retry 5 -L -o fpcup ${{ matrix.config.fpcup-url }}
        chmod +x fpcup
        mkdir lazarus
        ./fpcup --installdir=lazarus --fpcURL=${{ matrix.config.fpc-url }} --lazURL=${{ matrix.config.laz-url }} ${{ matrix.config.fpcup-opt }} --only=docker --noconfirm --verbose
    - name: Install AArch64 Cross Compiler
      if: matrix.config.name == 'AArch64'
      run: |
        curl --retry 5 -L -o libs.zip https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsLinuxAarch64.zip && unzip -o libs.zip -d lazarus/
        curl --retry 5 -L -o bins.zip https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.0/CrossBinsLinuxAarch64.zip && unzip -o bins.zip -d lazarus/cross/bin
        ./fpcup --installdir=lazarus --ostarget=linux --cputarget=aarch64 --only="FPCCleanOnly,FPCBuildOnly" --crossbindir=lazarus/cross/bin --crosslibdir=lazarus/cross/lib/aarch64-linux --noconfirm --verbose
    - name: Build the Main Application for all OS
      run: |
        lazbuild --build-mode=Release "source/project/tracker_editor/trackereditor.lpi"
    - name: Build the Unit Tests Application on windows only
      if: matrix.config.os == 'windows-latest'
      run: |
        lazbuild --build-mode=Debug "source/project/unit_test/tracker_editor_test.lpi"
    - name: Run headless test on windows only
      if: matrix.config.os == 'windows-latest'
      run: |
        ./enduser/test_trackereditor.exe -a --format=plain



